import mongoose from 'mongoose';

const blogPostSchema = new mongoose.Schema(
  {
    title: { type: String, required: true, trim: true },
    subtitle: { type: String },
    contentHtml: { type: String, required: true },
    summary: { type: String },

    bannerImageUrl: { type: String },
    imageUrls: [{ type: String }],

    category: { type: mongoose.Schema.Types.ObjectId, ref: 'Category' },
    tags: { type: [String] },

    author: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      index: true,
    },

    status: {
      type: String,
      enum: ['draft', 'pending', 'under_review' ,'scheduled', 'published', 'rejected'],
      default: 'pending',
      index: true,
    },
    
    scheduledAt: {
      type: Date,
      default: null,
      index: true,
    },

    rejectionReason: {
      type: String,
      default: null,
    },

    publishedAt: {
      type: Date, 
      index: true,
    },

    isDeleted: {
      type: Boolean,
      default: false,
      index: true,
    },

    deletedAt: {
      type: Date,
    },

    isFeatured: { type: Boolean, default: false, index: true },
    views: { type: Number, default: 0, index: true },
    likes: { type: Number, default: 0 },
    readingTimeMinutes: { type: Number, default: 0 },

    slug: { type: String, unique: true, index: true },

    metaTitle: { type: String },
    metaDescription: { type: String },
    seoKeywords: [{ type: String }],

    trendScore: { type: Number, default: 0, index: true },
    autoGeneratedBy: { type: String },
  },
  { timestamps: true }
);

blogPostSchema.index({
  title: 'text',
  subtitle: 'text',
  contentHtml: 'text',
});

export default mongoose.model('BlogPost', blogPostSchema);
